-- AlterTable
ALTER TABLE `Order` ADD COLUMN `coordinatorReceivedAt` DATETIME(3) NULL,
    ADD COLUMN `coordinatorReceivedBy` VARCHAR(191) NULL,
    ADD COLUMN `dropoffOtp` VARCHAR(191) NULL,
    ADD COLUMN `dropoffOtpAttempts` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `dropoffOtpExpiry` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `OrderEvent` MODIFY `type` ENUM('ORDER_CREATED', 'SELLER_NOTIFIED', 'SELLER_ACCEPTED', 'SELLER_REJECTED', 'SELLER_AUTO_REJECTED', 'SELLER_PROCESSING', 'SELLER_MARKED_READY', 'SELLER_DROPOFF_OTP_ISSUED', 'SELLER_DROPPED_OFF', 'COORDINATOR_RECEIVED', 'SELLER_MISSED_DROPOFF_DEADLINE', 'DELIVERER_ASSIGNED', 'DELIVERER_PICKUP_OTP_ISSUED', 'DELIVERER_PICKUP_OTP_VERIFIED', 'DELIVERER_CONFIRMED_PICKUP', 'HANDED_TO_DELIVERER', 'OUT_FOR_DELIVERY', 'BUYER_DELIVERY_OTP_ISSUED', 'BUYER_OTP_VERIFICATION_ATTEMPTED', 'BUYER_OTP_VERIFIED', 'DELIVERY_ATTEMPTED', 'DELIVERY_FAILED', 'DELIVERY_RETRY_SCHEDULED', 'RETURNED_TO_DROPOFF', 'DELIVERED', 'PARTIALLY_DELIVERED', 'ITEM_CANCELLED', 'REFUND_INITIATED', 'REFUND_COMPLETED', 'PAYOUT_PENDING', 'PAYOUT_PROCESSING', 'PAYOUT_SUCCESS', 'PAYOUT_FAILED', 'LATE_DELIVERY_FINE_ISSUED', 'LATE_DELIVERY_FINE_PAID', 'BUSINESS_DELIVERY_RESTRICTED', 'BUSINESS_DELIVERY_UNRESTRICTED', 'DISPUTE_OPENED', 'DISPUTE_RESOLVED') NOT NULL;

-- CreateTable
CREATE TABLE `MarketplaceSettings` (
    `id` VARCHAR(191) NOT NULL DEFAULT 'default',
    `dropoffWindowStart` VARCHAR(191) NOT NULL DEFAULT '17:00',
    `dropoffWindowEnd` VARCHAR(191) NOT NULL DEFAULT '19:00',
    `handoffWindowStart` VARCHAR(191) NOT NULL DEFAULT '15:00',
    `handoffWindowEnd` VARCHAR(191) NOT NULL DEFAULT '16:00',
    `updatedAt` DATETIME(3) NOT NULL,
    `updatedBy` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

