name: Snyk Scan (reusable)

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  snyk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
