name: opportunity-hub CI

on:
  push:
    paths:
      - "services/opportunity-hub/**"
  pull_request:
    paths:
      - "services/opportunity-hub/**"

jobs:
  security-scan:
    uses: ./.github/workflows/shared/snyk-scan-template.yml
    with:
      working-directory: services/opportunity-hub
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
